
server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmut_warehouse?serverTimezone=UTC
    username: root
    password: 123456



mybatis-plus:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.yf.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  # 开启生产环境屏蔽（可选）
  production: false

